# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

environment:
  global:
    RUST_VERSION: stable
    APPVEYOR_CACHE_SKIP_RESTORE: true
    CRATE_NAME: skeptic

  matrix:
    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

    # Testing other channels
    #- TARGET: x86_64-pc-windows-msvc
    #  RUST_VERSION: beta
    #- TARGET: x86_64-pc-windows-msvc
    #  RUST_VERSION: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  # remove clean once fixed https://github.com/budziq/rust-skeptic/issues/57
  #- cargo clean
  - cargo build --target %TARGET% --verbose
  #- cargo build --target %TARGET% --release
  - cargo test --target %TARGET% --verbose
  #- cargo test --target %TARGET% --release
  - cd src\skeptic
  - cargo build --target %TARGET% -- verbose
  #- cargo build --target %TARGET% --release
  - cargo test --target %TARGET% --verbose
  #- cargo test --target %TARGET% --release

cache:
  - C:\Users\appveyor\.cargo\registry

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
