[package]
name = "skeptic"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "Test your Rust markdown documentation via Cargo"
license = "MIT/Apache-2.0"
repository = "https://github.com/brson/rust-skeptic"

[lib]
path = "lib.rs"

[dependencies]
pulldown-cmark = "0.0.3"
